### ISSUE TITLE
Preprint code

### ISSUE THREAD

**Issue by seabbs** [mrc-ide/sarscov2-severity-england#1]
Hi, 

I've been enjoying [your preprint](https://www.medrxiv.org/content/10.1101/2023.02.10.23285516v1) and wondered when the ETA was for making the code public (this is the link given in both the paper and SI as being the source for the preprint code).

Sam

**Comment by pabloperguz** [comment]
Hi @seabbs many thanks for your comment. Please note the code is now public and includes indications on the package versions you would need to run the model.
Best wishes,
Pablo

**Comment by seabbs** [comment]
Thanks for pinging. I see that it just came out in Nature Comms.

**Comment by pabloperguz** [comment]
Apologies for the late reaction, Sam.
Best wishes, 
Pablo.
